services:
  mongo:
  image: mongo:4.4.6
  container_name: meu-mongo
  netwoks:
   - compose-bridge

nodedocker:
  image: wandersouza27/nodedocker:1.0
  container_name: nodedocker
  netwoks:
    - compose-bridge
  ports: 
    - 3000: 3000

networks:
  compose-bridge:
    driver: bridge